---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus

buildMetadata:
  - originAnnotations

resources:
  - https://github.com/prometheus-operator/kube-prometheus//
